
	
	
	SELECT * FROM "OPTM_APS_PRODOPER"
	select sum(""OPTM_QUANTITY"") from ""OPTM_FG_BTCHSER"" A  where A.""OPTM_OPERNO"" =(select top 1 ""U_O_OPERNO"" from ""@OPTM_PRODOPER"" A inner join ""@OPTM_PRODORDR"" B On A.""DocEntry"" = B.""DocEntry"" where B.""U_O_ORDRNO"" = ? and ""U_O_OPERNO"" < ? order by ""U_O_OPERNO"" desc) and A.""OPTM_WONO"" = ? AND IFNULL(A.""OPTM_STATUS"",'') in('S','C','') AND ""OPTM_REJECT""<>'Y'
	
	
	SELECT TOP 1 "OPER_ID" as "id" 
	FROM "OPTM_APS_PRODOPER"
	ORDER BY OPER_ID DESC
	
	
	SELECT TOP 1 "OPR_LINK_ID" as "id" 
	FROM "OPTM_APS_PRODOPER_LINKS" 
	ORDER BY "OPR_LINK_ID" DESC
	
	
 
SELECT * FROM "OPTM_APS_SCH_REF" 
SELECT * FROM "OPTM_APS_PRODOPER"
SELECT * FROM "OPTM_APS_PRODOPER_LINKS"
SELECT * FROM "OPTM_APS_DSHBD_SETTINGS"

truncate table "OPTM_APS_SCH_REF"; 
truncate table  "OPTM_APS_PRODOPER";
truncate table "OPTM_APS_PRODOPER_LINKS"; 
truncate table "OPTM_APS_DSHBD_SETTINGS";

DROP TABLE "OPTM_APS_SCH_REF"; 
DROP TABLE  "OPTM_APS_PRODOPER";
DROP TABLE "OPTM_APS_PRODOPER_LINKS"; 
DROP TABLE "OPTM_APS_DSHBD_SETTINGS";



SET SCHEMA "DEVQAHS40903"
CREATE COLUMN TABLE "OPTM_APS_SCH_REF" (
	OPTM_REF_ID integer NOT NULL  PRIMARY KEY  generated by default as IDENTITY, 
	OPTM_PLAN_NAME varchar(100) NOT NULL, 
	OPTM_FROM_DATE timestamp, 
	OPTM_TO_DATE timestamp, 
	OPTM_SCHEDULING_STATUS varchar(100), 
	OPTM_IS_DELETED tinyint
)

SELECT TOP 1 OPTM_REF_ID as ref_id FROM "OPTM_APS_SCH_REF" ORDER BY OPTM_REF_ID DESC  

SELECT "ID" AS "id", "NAME" AS "name", "VALUE" AS "VALUE", "GROUP" AS "grp" FROM OPTM_APS_DSHBD_SETTINGS 

INSERT INTO OPTM_APS_DSHBD_SETTINGS (NAME, VALUE, "GROUP") VALUES ('task_column_width', '50', 'system')


SELECT "OPTM_REF_ID" AS "ref_id", Cast("OPTM_FROM_DATE" as date) AS "from_date", cast("OPTM_TO_DATE" as date) AS "to_date", 
"OPTM_SCHEDULING_STATUS" AS "scheduling_status", "OPTM_IS_DELETED" AS "is_deleted", "OPTM_PLAN_NAME" AS "plan_name" 
FROM "OPTM_APS_SCH_REF"

SET SCHEMA DEVQAHS40903

SELECT "ID" AS "id", "NAME" AS "name","VALUE" AS "VALUE", "GROUP" AS "grp" FROM "OPTM_APS_DSHBD_SETTINGS"

SELECT "NAME" as "name" FROM "OPTM_APS_DSHBD_SETTINGS"


DROP TABLE OPTM_APS_DSHBD_SETTINGS; 
CREATE COLUMN TABLE "OPTM_APS_DSHBD_SETTINGS" (
ID integer NOT NULL  PRIMARY KEY  generated by default as IDENTITY, 
"NAME" varchar(150) NULL, 
"VALUE" text NULL, 
"GROUP" varchar(150) NULL
)

INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('default_work_center', 'all', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('task_column_width', '50', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('chart_table_row_height', '30', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('left_panel_width', '550', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('left_panel_resize', '1', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('enable_keyboard_shortcut', '1', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('chart_header_scale_height', '50', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('default_timeline_view', 'day', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('default_task_color_code', 'priority', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('drag_lightbox', '1', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('lightbox_additional_height', '120', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('default_theme', 'material', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('task_type_color_set', '{"1":{"task_color":"#000000","progress_color":"#000000"},"2":{"task_color":"#000000","progress_color":"#000000"},"3":{"task_color":"#9f55ba","progress_color":"#9113e5"},"4":{"task_color":"#d75252","progress_color":"#f60f0f"},"5":{"task_color":"#000000","progress_color":"#000000"},"6":{"task_color":"#cbdc3b","progress_color":"#a4c006"},"7":{"task_color":"#000000","progress_color":"#000000"},"8":{"task_color":"#000000","progress_color":"#000000"},"9":{"task_color":"#000000","progress_color":"#000000"}}', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('priority_color_set', '{"1":{"task_color":"#e2643c","progress_color":"#e50e1e"},"11":{"task_color":"#4ccf54","progress_color":"#10b336"},"31":{"task_color":"#427db8","progress_color":"#0747ae"}}', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('left_right_panel_font_size', '12', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME,  "VALUE", "GROUP") VALUES ('unhighlight_color', '#aaa7a8', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME, "VALUE", "GROUP") VALUES ('default_resource_load_layout', 'detail', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME, "VALUE", "GROUP") VALUES ('resource_balanced_color', '#42b849', 'system');
INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME, "VALUE", "GROUP") VALUES ('resource_overload_color', '#d96c49', 'system');

Select Length('task_color":"#000000","progress_color":"#000000"},"2":{"task_color":"#000000","progress_color":"#000000"},"3":{"task_color":"#9f55ba","progress_color":"#9113e5"},"4":{"task_color":"#d75252","progress_color":"#f60f0f"},"5":{"task_color":"#000000","progress_color":"#000000"},"6":{"task_color":"#cbdc3b","progress_color":"#a4c006"},"7":{"task_color":"#000000","progress_color":"#000000"},"8":{"task_color":"#000000","progress_color":"#000000"},"9":{"task_color":"#000000","progress_color":"#000000"}}') FROM DUMMY 

SELECT "ID" AS "id","GROUP" AS "grp","NAME" AS "name",
SUBSTRING(CAST("VALUE" AS varchar),1, 600) AS "second_part" 
FROM "OPTM_APS_DSHBD_SETTINGS";

SELECT "ID" AS "id", "GROUP" AS "grp", "NAME" AS "name", 
CONCAT(SUBSTRING(CAST("VALUE" AS varchar),1, 253), SUBSTRING(CAST("VALUE" AS varchar),254, 253)) as "value" 
FROM "OPTM_APS_DSHBD_SETTINGS"

SELECT START_DATE, END_DATE FROM OPTM_APS_PRODOPER

SELECt * FROM "@OPTMSHIFT_MASTER"

  SELECT "OPTM_SHIFTID" AS "shift_id", "OPTM_WHSCODE" AS "wh_id", "OPTM_WCID" AS "work_center_id", "OPTM_RESID" AS "resource", 
  "OPTM_WORKDATE" AS "shift_date", "U_O_START_TIME" AS "shift_start", "U_O_END_TIME" AS "shift_end", "U_O_BREAK_DURATION" AS "break_duration", 
  "U_O_AVL_TIME" AS "available_time", "U_OPTM_BRKSTRTTIME" AS "break_start_time" 
  FROM "OPTM_WC_RES_CAPACITY" as "res_cap" 
  LEFT OUTER JOIN "@OPTMSHIFT_MASTER" as  "shift_tb" ON "shift_tb"."Code" = "res_cap"."OPTM_SHIFTID" 
  ORDER BY "OPTM_WCID"
  
  SELECT "OPTM_SHIFTID" AS "shift_id", "OPTM_AVAILABLE_CAPACITY" AS "avail_capacity", "OPTM_USED_CAPACITY" AS "used_capacity", 
  "OPTM_BAL_CAPACITY" AS "bal_capacity", "OPTM_WHSCODE" AS "wh_id", "OPTM_WCID" AS "work_center_id", "OPTM_RESID" AS "resource", 
  "OPTM_WORKDATE" AS "shift_date", "U_O_START_TIME" AS "shift_start", "U_O_END_TIME" AS "shift_end", 
  "U_O_BREAK_DURATION" AS "break_duration", "U_O_AVL_TIME" AS "available_time", "U_OPTM_BRKSTRTTIME" AS "break_start_time" 
  FROM "OPTM_WC_RES_CAPACITY" as "res_cap" 
  LEFT OUTER JOIN "@OPTMSHIFT_MASTER" as "shift_tb" ON "shift_tb"."Code" = "res_cap"."OPTM_SHIFTID" 
  ORDER BY "OPTM_WCID"
  
  
  	 -- get aps operations 
	SELECT DISTINCT wo.OPER_ID AS "parent",
	(SELECT
	 MAX("OPER_ID")
		FROM "OPTM_APS_PRODOPER" as temp_aps_src
		where 
		CAST(temp_aps_src."OPERATION_NUMBER" AS integer) < CAST(task."OPERATION_NUMBER" AS integer) 
		AND "WORK_ORDER_ID" = wo."WORK_ORDER_ID" 
		AND "OPERATION_TYPE" = 'task' 
	) AS "source_id",
	task.OPER_ID AS "id",  task.REF_ID AS "ref_id",  task.HEAD_DOC_ENTRY AS "head_doc_entry",  task.OPER_DOC_ENTRY AS "oper_doc_entry",  task.OPER_LINE_ID AS "oper_line_id",  task.RES_LINE_ID AS "res_line_id",  task."OPERATION_TYPE" AS "operation_type",  task.TASK_TYPE AS "task_type",  task.WORK_CENTER_ID AS "work_center_id",  task."WORK_ORDER_ID" AS "work_order_id",  task.RESOURCE_ID AS "resource_id",  task.RESOURCE_NAME AS "resource_name",  task.PLANNED_RESOURCE_ID AS "planned_resource_id",  task.PLANNED_RESOURCE_NAME AS "planned_resource_name",  task.OPERATION_NUMBER AS "operation_number",  task.OPERATION_CODE AS "operation_code",  task.DESCRIPTION AS "description",  task.PRIORITY AS "priority",  task.READONLY AS "readonly",  task.STATUS AS "status",  task.START_DATE AS "start_date",  task.END_DATE AS "end_date",  task.DURATION AS "duration",  task.MIN_DURATION AS "min_duration",  task.PROGRESS AS "progress",  task.IS_LOCAL_TASK AS "is_local_task",  task.IS_DELETED AS "is_deleted",  task.SPLIT_TASK_GRP_ID AS "split_task_grp_id",  task."required_resource" 
	FROM "OPTM_APS_PRODOPER" as task 
	LEFT OUTER JOIN "OPTM_APS_PRODOPER" wo ON task."WORK_ORDER_ID" = wo.OPERATION_CODE 
	AND task.OPER_DOC_ENTRY = wo.HEAD_DOC_ENTRY 
	AND wo."OPERATION_TYPE" = 'project' 
	WHERE  task."REF_ID" = '4'  AND  task.IS_DELETED = '0' 
	ORDER BY task."WORK_ORDER_ID", task."OPERATION_NUMBER", "id" ASC
  
  
  -- update links 
  UPDATE "OPTM_APS_PRODOPER_LINKS" SET REF_ID='5', PRED_TASK_ID='335', SUCC_TASK_ID='288', CONNECTION_TYPE='1' WHERE OPR_LINK_ID = '75'
  
  ALTER TABLE "@OPTM_PRODORDR" ADD ("U_OPTM_PROGRESS" integer);
ALTER TABLE "@OPTM_PRODORDR" ADD ("U_OPTM_OPERPROGRESS" integer);


INSERT INTO "OPTM_APS_DSHBD_SETTINGS" (NAME, "value", "group") VALUES ('enable_year_view_scale', '1', 'system')
  
