CREATE COLUMN TABLE "OPTM_APS_PRODOPER" ( OPER_ID integer NOT NULL PRIMARY KEY,
	 REF_ID varchar(100) NOT NULL,
	 HEAD_DOC_ENTRY varchar(20) NOT NULL,
	 OPER_DOC_ENTRY varchar(20) NOT NULL,
	 OPER_LINE_ID varchar(20) NOT NULL,
	 RES_LINE_ID varchar(20) NOT NULL,
	 OPERATION_TYPE varchar(20) NOT NULL,
	 TASK_TYPE varchar(20) NOT NULL,
	 WORK_CENTER_ID varchar(100) NOT NULL,
	 WORK_ORDER_ID varchar(100) NOT NULL,
	 RESOURCE_ID varchar(100) NOT NULL,
	 RESOURCE_NAME varchar(100) NOT NULL,
	 PLANNED_RESOURCE_ID varchar(100) NOT NULL,
	 PLANNED_RESOURCE_NAME varchar(100) NOT NULL,
	 OPERATION_NUMBER varchar(100) NOT NULL,
	 OPERATION_CODE varchar(100) NOT NULL,
	 DESCRIPTION varchar(100) NOT NULL,
	 PRIORITY varchar(100) NOT NULL,
	 READONLY tinyint,
	 STATUS varchar(50) NOT NULL,
	 START_DATE timestamp,
	 END_DATE timestamp,
	 DURATION varchar(50) NOT NULL,
	 MIN_DURATION varchar(50) NOT NULL,
	 PROGRESS varchar(50) NOT NULL,
	 IS_LOCAL_TASK tinyint,
	 IS_DELETED tinyint,
	 SPLIT_TASK_GRP_ID varchar(100) NULL )
;
 SELECT
	 * 
FROM "OPTM_APS_PRODOPER"
;
 ALTER TABLE "OPTM_APS_PRODOPER" ADD ("required_resource" integer)
;
 CREATE COLUMN TABLE "OPTM_APS_PRODOPER_LINKS" ( OPR_LINK_ID integer NOT NULL PRIMARY KEY generated by default as IDENTITY,
	 REF_ID varchar(100) NOT NULL,
	 PRED_TASK_ID varchar(20) NOT NULL,
	 SUCC_TASK_ID varchar(20) NOT NULL,
	 CONNECTION_TYPE varchar(20) NOT NULL)
;
 CREATE COLUMN TABLE "OPTM_APS_DSHBD_SETTINGS" ( ID integer NOT NULL PRIMARY KEY generated by default as IDENTITY,
	 NAME varchar(400) NULL,
	 VALUE text NULL,
	 "GROUP" varchar(150) NULL ) SELECT
	 * 
FROM "OPTM_APS_DSHBD_SETTINGS" truncate table "OPTM_APS_DSHBD_SETTINGS" INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('default_work_center',
	 '$post_data[default_work_center]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('task_column_width',
	 '$post_data[task_column_width]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('chart_table_row_height',
	 '$post_data[chart_table_row_height]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('left_panel_width',
	 '$post_data[left_panel_width]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('left_panel_resize',
	 '$post_data[left_panel_resize]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('enable_keyboard_shortcut',
	 '$post_data[enable_keyboard_shortcut]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('chart_header_scale_height',
	 '50',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('default_timeline_view',
	 '$post_data[default_timeline_view]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('default_task_color_code',
	 '$post_data[default_task_color_code]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('drag_lightbox',
	 '$post_data[drag_lightbox]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('lightbox_additional_height',
	 '$post_data[lightbox_additional_height]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('default_theme',
	 '$post_data[default_theme]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('task_type_color_set',
	 '$post_data[task_type_color_set_json]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('priority_color_set',
	 '$post_data[priority_color_set_json]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('left_right_panel_font_size',
	 '$post_data[left_right_panel_font_size]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('unhighlight_color',
	 '$post_data[unhighlight_color]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('default_resource_load_layout',
	 '$post_data[default_resource_load_layout]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('resource_balanced_color',
	 '$post_data[resource_balanced_color]',
	 'system')
;
INSERT 
INTO OPTM_APS_DSHBD_SETTINGS (NAME,
	 VALUE,
	 "GROUP") VALUES ('resource_overload_color',
	 '$post_data[resource_overload_color]',
	 'system')
;
 TRUNCATE TABLE OPTM_APS_DSHBD_SETTINGS SELECT
	 * 
FROM OPTM_APS_DSHBD_SETTINGS -- work center master query
SELECT
	 DISTINCT prod_res.U_O_WC_ID,
	 wc_msg."Code" AS "id",
	 wc_msg."Name" AS "name" 
FROM "@OPTM_PRODRES" prod_res 
LEFT OUTER JOIN "@OPTMWC_MST" wc_msg ON prod_res.U_O_WC_ID = wc_msg."Code" 
WHERE U_O_WC_ID != ''
;
 -- work order query 
 SELECT
	 OPERATION_CODE AS "work_order_number" 
FROM "OPTM_APS_PRODOPER" 
WHERE OPERATION_TYPE = 'project'
;
 SELECT
	 DISTINCT U_O_WC_ID AS "work_center_id",
	 U_O_RESID AS "id",
	 U_O_RESDESC AS "name" 
FROM "@OPTM_PRODRES" 
WHERE U_O_RESID != ''
;
 SELECT
	 U_O_WC_ID AS "work_center_id",
	 wc_msg."Name" AS "work_center_name",
	 U_O_RESID AS "resource_id",
	 U_O_RESDESC AS "resource_name" 
FROM "@OPTM_PRODRES" prod_res 
LEFT OUTER JOIN "@OPTMWC_MST" wc_msg ON prod_res.U_O_WC_ID = wc_msg."Code" 
WHERE U_O_RESID != ''
;
 SELECT
	 DISTINCT U_O_WC_ID AS "work_center_id",
	 A."DocEntry" AS "head_doc_entry",
	 A.U_O_ORDRNO AS "id",
	 A.U_O_ORDRNO AS "work_order_id",
	 A.U_O_ORDRNO AS "name",
	 A.U_O_ORDRNO AS "description",
	 U_O_STARTDATE AS "start_date",
	 A.U_O_ENDDATE AS "end_date",
	 A.U_OPTM_PRIORITY AS "priority",
	 C.U_O_ISSTOOPER AS "res_operation_number",
	 A.U_OPTM_STRTTIME AS "start_time",
	 A.U_OPTM_ENDTIME AS "end_time" 
FROM "@OPTM_PRODORDR" A 
INNER JOIN "@OPTM_PRODRES" C ON A."DocEntry" = C."DocEntry" 
WHERE U_O_WC_ID != ''
;
 UPDATE \"@OPTM_PRODORDR\" 
SET U_OPTM_PRIORITY = '$task_details[priority]',
	 U_O_STARTDATE = '$task_details[start_date]',
	 U_OPTM_STRTTIME = '$task_details[start_time]',
	 U_O_ENDDATE = '$task_details[end_date]',
	 U_OPTM_ENDTIME = '$task_details[end_time]' 
WHERE U_O_ORDRNO = '$task_details[operation_code]' 
AND "DocEntry" = '$task_details[head_doc_entry]';


  SELECT
	 DISTINCT wo.OPER_ID AS "parent",
	 (SELECT OPER_ID 
	FROM "OPTM_APS_PRODOPER" 
	WHERE CAST("OPERATION_NUMBER" AS integer) < CAST(task.OPERATION_NUMBER AS integer) 
	AND WORK_ORDER_ID = wo.WORK_ORDER_ID 
	AND "OPERATION_TYPE" = 'task' 
	-- ORDER BY CAST(OPERATION_NUMBER AS integer) DESC
	) AS "source_id",
	 task.OPER_ID AS "id",
	 task.REF_id AS "ref_id",
	 task.HEAD_DOC_ENTRY AS "head_doc_entry",
	 task.OPER_DOC_ENTRY AS "oper_doc_entry",
	 task.OPER_LINE_ID AS "oper_line_id",
	 task.RES_LINE_ID AS "res_line_id",
	 task."OPERATION_TYPE" AS "operation_type",
	 task.TASK_TYPE AS "task_type",
	 task.WORK_CENTER_ID AS "work_center_id",
	 task."WORK_ORDER_ID" AS "work_order_id",
	 task.RESOURCE_ID AS "resource_id",
	 task.RESOURCE_NAME AS "resource_name",
	 task.PLANNED_RESOURCE_ID AS "planned_resource_id",
	 task.PLANNED_RESOURCE_NAME AS "planned_resource_name",
	 task.OPERATION_NUMBER AS "operation_number",
	 task.OPERATION_CODE AS "operation_code",
	 task.DESCRIPTION AS "description",
	 task.PRIORITY AS "priority",
	 task.READONLY AS "readonly",
	 task.STATUS AS "status",
	 task.START_DATE AS "start_date",
	 task.END_DATE AS "end_date",
	 task.DURATION AS "duration",
	 task.MIN_DURATION AS "min_duration",
	 task.PROGRESS AS "progress",
	 task.IS_LOCAL_TASK AS "is_local_task",
	 task.IS_DELETED AS "is_deleted",
	 task.SPLIT_TASK_GRP_ID AS "split_task_grp_id",
	 task."required_resource" 
FROM "OPTM_APS_PRODOPER" as task 
LEFT OUTER JOIN "OPTM_APS_PRODOPER" wo ON task."WORK_ORDER_ID" = wo.OPERATION_CODE 
AND task.OPER_DOC_ENTRY = wo.HEAD_DOC_ENTRY 
AND wo."OPERATION_TYPE" = 'project' 
ORDER BY task."WORK_ORDER_ID",
	 task."OPERATION_NUMBER",
	 "id" ASC
	 
	 
	 SELECT CONVERT(datetime, "hh:mi:ss:mmm", START_DATE) as start_date, cast(END_DATE as date) 
	 
	 SELeCT to_timestamp("START_DATE",'YYYY-MM-DD HH24:MI:SS') , START_DATE FROM OPTM_APS_PRODOPER
	 SELECT START_DATE, END_DATE FROM OPTM_APS_PRODOPER
	select * From "OPTM_TASKLIST"
	
	
	SELECT TO_TIMESTAMP ('2010-01-11 13:30:00', 'YYYY-MM-DD h:i:s') "to timestamp" FROM DUMMY;
	
	SELECT to_date('2010-Aug-09 02:00:01 PM' , 'yyyy-Mon-dd HH:MI:SS AM') "date"
  FROM DUMMY;
  
  SELECT "OPTM_SHIFTID" AS "shift_id", "OPTM_WHSCODE" AS "wh_id", "OPTM_WCID" AS "work_center_id", "OPTM_RESID" AS "resource", 
  "OPTM_WORKDATE" AS "shift_date", "U_O_START_TIME" AS "shift_start", "U_O_END_TIME" AS "shift_end", "U_O_BREAK_DURATION" AS "break_duration", 
  "U_O_AVL_TIME" AS "available_time", "U_OPTM_BRKSTRTTIME" AS "break_start_time" 
  FROM "OPTM_WC_RES_CAPACITY" as "res_cap" 
  LEFT OUTER JOIN "@OPTMSHIFT_MASTER" as  "shift_tb" ON "shift_tb"."code" = "res_cap"."OPTM_SHIFTID" 
  ORDER BY "OPTM_WCID"
  
  
SELECT prod_opr.U_OPTM_OPERPROGRESS, prod_head.U_OPTM_PROGRESS, prod_opr.U_O_OPR_ID, 
prod_head.U_O_ORDRNO, prod_head."DocEntry" AS "head_doc_entry", 
prod_opr."DocEntry" AS "oper_doc_entry", prod_opr."LineId" AS "oper_line_id", 
"OPER_ID", "REF_ID" 
FROM "@OPTM_PRODOPER" prod_opr 
INNER JOIN "@OPTM_PRODORDR" prod_head ON prod_head."DocEntry" = prod_opr."DocEntry" 
LEFT OUTER JOIN "OPTM_APS_PRODOPER" aps_opr 
ON aps_opr."HEAD_DOC_ENTRY" = prod_head."DocEntry" 
WHERE prod_head.U_O_STATUS <> '3' AND prod_head.U_O_STATUS <> '4' 
AND (prod_opr.U_OPTM_OPSDATE BETWEEN '2010-04-01 00:00' AND '2019-04-01 00:00') 
AND "REF_ID" = '5' ORDER BY U_O_ORDRNO, prod_opr.U_O_OPR_ID ASC


SELECT DISTINCT wo.OPER_ID AS "parent",
	(SELECT
	 MAX("OPER_ID")
		FROM "OPTM_APS_PRODOPER" as temp_aps_src
		where 
		CAST(temp_aps_src."OPERATION_NUMBER" AS integer) < CAST(task."OPERATION_NUMBER" AS integer) 
		AND "WORK_ORDER_ID" = wo."WORK_ORDER_ID" 
		AND "OPERATION_TYPE" = 'task' 
	) AS "source_id",
	task.OPER_ID AS "id",  task.REF_ID AS "ref_id",  task.HEAD_DOC_ENTRY AS "head_doc_entry",  task.OPER_DOC_ENTRY AS "oper_doc_entry",  task.OPER_LINE_ID AS "oper_line_id",  task.RES_LINE_ID AS "res_line_id",  task."OPERATION_TYPE" AS "operation_type",  task.TASK_TYPE AS "task_type",  task.WORK_CENTER_ID AS "work_center_id",  task."WORK_ORDER_ID" AS "work_order_id",  task.RESOURCE_ID AS "resource_id",  task.RESOURCE_NAME AS "resource_name",  task.PLANNED_RESOURCE_ID AS "planned_resource_id",  task.PLANNED_RESOURCE_NAME AS "planned_resource_name",  task.OPERATION_NUMBER AS "operation_number",  task.OPERATION_CODE AS "operation_code",  task.DESCRIPTION AS "description",  task.PRIORITY AS "priority",  task.READONLY AS "readonly",  task.STATUS AS "status",  task.START_DATE AS "start_date",  task.END_DATE AS "end_date",  task.DURATION AS "duration",  task.MIN_DURATION AS "min_duration",  task.PROGRESS AS "progress",  task.IS_LOCAL_TASK AS "is_local_task",  task.IS_DELETED AS "is_deleted",  task.SPLIT_TASK_GRP_ID AS "split_task_grp_id",  task."required_resource" 
	FROM "OPTM_APS_PRODOPER" as task 
	LEFT OUTER JOIN "OPTM_APS_PRODOPER" wo ON task."WORK_ORDER_ID" = wo.OPERATION_CODE 
	AND task.OPER_DOC_ENTRY = wo.HEAD_DOC_ENTRY 
	AND wo."OPERATION_TYPE" = 'project' 
	WHERE  task."REF_ID" = '1'  AND  task.IS_DELETED = '0' 
	ORDER BY task."WORK_ORDER_ID", task."OPERATION_NUMBER", "id" ASC 
	
	SELECT X."id", X."head_doc_entry", X."oper_doc_entry", X."oper_line_id", X."res_line_id", X."work_center_id", X."work_order_id", X."resource_id", X."resource_name", X."operation_number", X."operation_code", X."description", X."priority", X."readonly", X."status", X."start_date", X."end_date", X."duration", X."progress", X."res_operation_number", X."opr_start_time", X."opr_end_time", X."required_resource" FROM (SELECT ROW_NUMBER() OVER (PARTITION BY A."U_O_ORDRNO", C."U_O_OPERNO" ORDER BY (CASE WHEN IFNULL(G."U_OPTM_SCHEDULE",'N') = 'N' THEN 1 ELSE 0 END), G."LineId") AS "row_number", ROW_NUMBER() OVER ( ORDER BY A.U_O_ORDRNO, C.U_O_OPERNO, G."LineId" ASC) AS "id", A."DocEntry" AS "head_doc_entry", C."DocEntry" AS "oper_doc_entry", C."LineId" AS "oper_line_id", G."LineId" AS "res_line_id", G.U_O_WC_ID AS "work_center_id", A.U_O_ORDRNO AS "work_order_id", G.U_O_RESID AS "resource_id", G.U_O_RESDESC AS "resource_name", C.U_O_OPERNO AS "operation_number", C.U_O_OPR_ID AS "operation_code", C.U_O_OPR_DESC AS "description", A.U_OPTM_PRIORITY AS "priority", C.U_OPTM_LOCKED AS "readonly", C.U_O_OPERCMPFLG AS "status", C.U_OPTM_OPSDATE AS "start_date", C.U_OPTM_OPEDATE AS "end_date", C.U_OPTM_OPLTHRS AS "duration", ((C.U_O_CUMPRDCDQTY / A.U_O_ORDRQTY) * 100) AS "progress", G.U_O_ISSTOOPER AS "res_operation_number", C.U_OPTM_OPSTIME AS "opr_start_time", C.U_OPTM_OPETIME AS "opr_end_time", G.U_O_RESSEQ AS "required_resource" FROM "@OPTM_PRODORDR" A INNER JOIN "@OPTM_PRODOPER" C ON A."DocEntry" = C."DocEntry" INNER JOIN "@OPTM_PRODRES" G ON A."DocEntry" = G."DocEntry" AND C.U_O_OPERNO = G.U_O_ISSTOOPER INNER JOIN "@OPTMPRD_ROUT_HDR" B ON A.U_O_PRODID = B.U_O_PRODUCT_NO AND A.U_O_RUTNGSEQ = B. U_O_ROUT_SEQ AND A.U_O_RTNGREV = B.U_O_REVI_NO INNER JOIN "@OPTMPRD_ROUT_LINE" D ON B."Code" = D."Code" AND C.U_O_OPERNO = D.U_O_LINE_NO INNER JOIN "@OPTMPRD_ROU_LN_RES" F ON B."Code" = F."Code" AND D."LineId" = F.U_O_ROUTLINE AND D.U_O_LINE_NO = F.U_O_LINE_NO INNER JOIN "@OPTMWC_MST" E ON D.U_O_WC_ID = E."Code" WHERE A.U_O_STATUS <> '3' AND A.U_O_STATUS <> '4') AS X WHERE X."row_number" = 1 AND (X."start_date" BETWEEN '2017-04-01 00:00' AND '2019-04-01 00:00') ORDER BY X."operation_number" ASC